GET http://localhost:5000/courses HTTP/1.1

###
GET http://localhost:5000/streams/active HTTP/1.1

###
GET http://localhost:5000/streams/archive HTTP/1.1

###
GET http://localhost:5000/users HTTP/1.1
Cookie: token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTg0NjIwOTksImV4cCI6MjA3ODQ2MjA5OSwic3ViIjoiNWY0NTE4MzVhNzIwYjc1ZWM0MDYyZWI0In0.RsW_EBid7RkdpFfs7CUTSjd9xQw51_vtR92wTdcZtcbXAGGJxup0bg0qYLjUmghM8h0fh_gkmhax24j-1Npiit_r0jf5ZP-VCFQF1lUZJGvG-21hmnxedXaO-D-saiWJzdodMNmMBFUrC5jbRnUKbWmEi6zoY4PtHngFqczkRnc; Path=/; HttpOnly; Secure

###
POST http://localhost:5000/users HTTP/1.1

###
GET http://localhost:5000/login HTTP/1.1

###
POST http://127.0.0.1:5000/login HTTP/1.1
content-type: application/json

{
    "name": "Ivan Ivanov",
    "password": "12345"
}

###
POST http://localhost:5000/logout HTTP/1.1
